<h2>Questions</h2>

<?php

$questions = $this->getHelper('Questions')->getQuestions();

?>

<p><a href="/newquestion">Submit a new question</a></p>

<p>Showing <?php echo $questions->count(); ?> questions</p>
<table border="1">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Asked by</th>
        <th>Asked on</th>
        <th>Answers</th>
    </tr>
<?php foreach ($questions as $question) { ?>
    <tr>
        <th><a href="/question/id/<?php echo $question->id; ?>"><?php echo $question->title; ?></a></th>
        <td><?php echo htmlspecialchars($question->description); ?></td>
        <td><?php echo htmlspecialchars($question->nickname); ?></td>
        <td><?php echo $question->created_on->getFormatted(); ?></td>
        <td><?php echo $question->num_answers; ?></td>
    </tr>
<?php } ?>
</table>
